"""
utils.py

Contains utility functions used in various parts of the library
"""

def traverse(edxobj):
    """
    Returns a generator that traverses a given object and all its children recursively

    This allows routines to traverse an entire course by using:
    for obj in traverse(course):
        (do something with every obj in the course)

    :param edxobj: EdxObject to traverse
    :return: Generator of EdxObjects
    """
    # Generate this object
    yield edxobj

    # Generate every object generated by the children of this object
    for child in edxobj.children:
        for entry in traverse(child):
            yield entry
